(defn find-multi [s ss]
 (loop [ini 0
        result []]
     
     (let [pos (clojure.string/index-of s ss ini)]
        (if (nil? pos)
           result
           (recur (inc pos) (conj result (inc pos)))))

))

(println (find-multi "AACAACCGTCGGAACAACCGGTAACAACCGCTAACAACCAACAACCCTTCGAACAACCCAACAACCGCAACAACCCTGAACAACCGAACAACCTTCGAACAACCTTTTAGATGACGCGTTACAACAACCAATAACAACCCGAACAACCAACAACCCAAACAACCATGCTTGAAACAACCCGTCAACAACCCAACAACCTTTCAACAACCGTCCAAACAACCAACAACCCTAGGCGGGAACAACCGCACTTAACAACCTGTGACGCTAACAACCCAACAACCCATCAACAACCCAGAAACAACCCAACAACCGAACAACCGGAACAACCGTTAACAACCAACAACCGCCAACAACCAAACAACCAACAACCAGTATAACAACCCCGCAAACAACCAACAACCCGAACAACCGGAACAACCAACAACCAACAACCAACAACCAACAACCCCATACTAACAACCGAAAACAACCCTCCTCGAAACAACCGATGTATCCAAGTTTAGGCAACAACCAACAACCACAGAACAACCGAACAACCAACAACCAACAACCGCTGAGACTGAGTAACAACCAACAACCATTAACAACCGTCATTAACAACCGTATACAACAACCCCAAACAACCCCAAACAACCAAACAACCAACAACCGAACAACCTATATATAAACAACCAACAACCAAACAACCGAACAACCCAACAACCGAACAACCTGGACTCGGCAACAACCAACAACCAACAACCCCTAACAACCAACAACCTAACAACCCTGTAACAACCAACAACCAGAACAACCTAAACAACCTAACAACCGCATGTGCACTAACAACCTGGATAACAACCAACAACCAACAACCGAACAACCCAACAACCGTGTCCAACAACCGTAAAACAACCATAACAACC" "AACAACCAA"))
